module.exports = {
    firstName: 'John',
    middleName: 'C',
    lastName: 'Yu',
    suffix: 'JCY',
    addressOne: '123 Fake Street',
    addressTwo: '#711',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90007',
    phone: '617-123-4567',
    debit: '4444555566667777',
    creditCard: 'VISA',
    donationAmt: '100',
    dateOfDonation: '09/14/17',
    multiDonation: 'Muti-donation',
    venue: 'Fenway',
    venueCity: 'Boston',
    venueState: 'MA',
    dateOfEvent: '09/14/17',
    timeOfEvent: '17:00',
    artistEvent: 'Red Sox Game',
    seatGrab: '35D',
    prizeOne: 'Amazon Gift Card',
    priceTwo: 'Walmart Gift Card',
    raffle50: 'Raffle',
    reelOne: 'Reel 1',
    reelTwo: 'Reel 2',
    keyCode: '12345678',
    vet: 'NO',
    vetRelated: 'NO',
    thermometer: 'false',
    noThermometer: 'true',
    announcer: 'false',
    noAnnouncer: 'true',
    email: 'john@crs-consulting.com',
    raffle: 'Apple iPhone',
    raffleFee: '1',
    sweeps: 'Apple Computer',
    sweepsFee: '1'
  }
  